name: Run Minimo .NET Server

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      DOTNET_ROLL_FORWARD: "Major"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK 9.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore ./Minimo_Server/Minimo_Server

      - name: Build Project
        run: dotnet build --configuration Release ./Minimo_Server/Minimo_Server

      - name: Run .NET Server
        run: dotnet run --configuration Release --project ./Minimo_Server/Minimo_Server
